# Generated by Django 5.2.8 on 2025-11-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChildCriteria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='metaapp.achievement')),
                ('parent_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_criteria', to='metaapp.criteria')),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='childcriteria',
            name='parent_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='metaapp.criteria'),
        ),
    ]
